name: tyb-tests-api

on:
  schedule:
    - cron:  '0 1 * * *'    # Run every day at 01:00 UTC
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
env:
  BASE_URL: https://tyb-stage.world

jobs:
  apiTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install
        working-directory: api-automation

      - name: run api tests
        run: yarn test
        working-directory: api-automation

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: api-automation/allure-results
          gh_pages: gh-pages/api
          allure_report: allure-report
          allure_history: allure-history
          subfolder: api
          keep_reports: 120

      - name: Move allure report to publish folder
        run: |
          mkdir ./publish_allure_results
          cp -R ./allure-history/. ./publish_allure_results
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish_allure_results
          destination_dir: api

      - name: Adding Report Link
        if: always()
        run: echo "###  API Automation Result here :rocket:! https://qaborepo.github.io/jcactions/api/$GITHUB_RUN_NUMBER/" >> $GITHUB_STEP_SUMMARY
